### ISSUE TITLE
No permission to create comment

### ISSUE THREAD

**Issue by sudo-bmitch** [fgrosse/go-coverage-report#15]
While trying out this action, I'm encountering the error: "GraphQL: Resource not accessible by integration (addComment)".

I tried passing the `GITHUB_TOKEN` environment variable, setting the `pull-requests: write` permission on the workflow rather than only the job, and adding the `issues: write` permission, but so far no luck. My best guess is that the `gh` command is running in the context of your repository instead of my own.

Here's an example run: https://github.com/regclient/regclient/actions/runs/8484759635/job/23248287252?pr=706

(Note that I have `continue-on-error: true` defined on the job so that it always shows as successful.)

**Comment by captainbeardo** [comment]
This set of permissions I have set on my job that works are:

```
   permissions:
      contents: read
      pull-requests: write
      packages: read
      actions: read
```

That is only set on the job and I don't pass in `GITHUB_TOKEN`. I do have the coverage in an entirely separate job than the steps generating the coverage. I don't think that makes it work, but that is a difference.

**Comment by fgrosse** [comment]
You can see at the top of your run when you expand the "Set up job" step and then click on `GITHUB_TOKEN Permissions`, that it actually has the wrong permissions (`PullRequests: read`) for some reason:

![image](https://github.com/fgrosse/go-coverage-report/assets/733004/a53a4111-741c-4cd2-9281-0e6b1d32c94a)

Just a hunch but can you check if you defined a variable or secret called `GITHUB_TOKEN` that is automatically passed into your jobs? You can check here: https://github.com/regclient/regclient/settings/secrets/actions

The reason why I am asking is because `GITHUB_TOKEN` is listed as environment variable in the log of your job (next to `GH_TOKEN`): 
![image](https://github.com/fgrosse/go-coverage-report/assets/733004/43c3565e-9ae9-4f8b-900e-92234c6974e6)

In my [own working tests](https://github.com/fgrosse/prioqueue/actions/runs/8566832918/job/23477385736?pr=3), the `GITHUB_TOKEN` is not defined as environment variable to the job step even though I copied your `permissions settings`.

**Comment by sudo-bmitch** [comment]
There's no `GITHUB_TOKEN` secret explicitly defined, that's getting generated by GH for the individual workflow, and the quickly expires. Passing it through was an attempt to fix the issue since I've seen it used on actions like github.com/actions/stale and github.com/softprops/action-gh-release. Setting the top level permissions is flagged by the OpenSSF Scorecard, but they were opened up and retried with different variations without any luck.

**Comment by fgrosse** [comment]
Not sure how to proceed here as the issue seems to be in your repository or workflow/job configuration. 

I checked on [a recent job run][1] in your repo and verified the same issue I  tried to explain in my last comment. The `GITHUB_TOKEN` Permissions are set to `PullRequests: read` but you need write access to comment on PRs.

![image](https://github.com/fgrosse/go-coverage-report/assets/733004/927ad79a-d7d1-495f-ad55-d45091a61f28)


Interestingly I also found [another run][2] in your repository which was triggered by merging into your main branch. In this case, the permissions are set to `PullRequests: write`.

[1]: https://github.com/regclient/regclient/actions/runs/8500528996/job/23282477665
[2]: https://github.com/regclient/regclient/actions/runs/8500536624/job/23282493740

**Comment by fgrosse** [comment]
To debug this, you can try if there is any effect when you remove the top-level `permissions` field. Since you only have a single job in your `Coverage Report` workflow, it shouldn't actually change any semantics the way I understand it because job level permissions would overwrite default permissions if I understood [the help page][1] correctly. 

Unfortunately the help doesn't state explicitly what happens if you set both the workflow and job permissions but it says you can _either_ do one _or_ the other but I suppose that's probably not meant in a strict way :shrug: 

> You can use permissions either as a top-level key, to apply to all jobs in the workflow, or within specific jobs.

Good luck!

[1]: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

**Comment by sudo-bmitch** [comment]
> I checked on [a recent job run](https://github.com/regclient/regclient/actions/runs/8500528996/job/23282477665) in your repo and verified the same issue I tried to explain in my last comment. The GITHUB_TOKEN Permissions are set to PullRequests: read but you need write access to comment on PRs.

Looks like that is on the pull request open action, and the branch is my personal fork rather than the regclient project repo, so I'm guessing GitHub security is blocking the GitHub action from getting access to my personal fork, or maybe it's blocking the fork from getting access to the project.

> To debug this, you can try if there is any effect when you remove the top-level permissions field.

Removing the top level permissions was [one of the things I tested](https://github.com/regclient/regclient/commit/20c296eb15f2ed9ddd45d04f30be223bb1a372cc) without luck, and [adding the write permission](https://github.com/regclient/regclient/commit/b0f728c5b7cbcf0d958567b735964f57039bcfb7) there also didn't help.

I'll revisit this later when I have more time to see if I can sort out the difference in token permissions.

**Comment by sudo-bmitch** [comment]
A quick check of the GITHUB_TOKEN permissions shows that GitHub removes all write access from the token on pull requests from a fork of a public repository. I'm going to need to do some more homework on if I want to change that setting since it's there for security reasons that I probably want.

https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

**Comment by fgrosse** [comment]
Yeah that makes sense. I didn't really think about forks yet but I think this action wouldn't work well for them exactly because of these (sensible) security defaults :thinking:

**Comment by sudo-bmitch** [comment]
I believe the workaround would be to use [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target), but that comes with a big security warning to not checkout code that was submitted by the user. The risk is probably fairly small for a job that can only update the pull request and that doesn't execute any of the code that is checked out. But given the added risk I'm going to put this on my backlog to revisit sometime when I have more availability.

Feel free to close this issue out if it's not a scenario you want to work on. Overall, I still think this is a neat idea that fills a need. So even if I'm not able to use it, thanks for creating it!

**Comment by fgrosse** [comment]
I ended up mentioning this under ["Limitations" in the README.md](https://github.com/fgrosse/go-coverage-report?tab=readme-ov-file#limitations) . Thanks again for pointing out this issue and helping to debug it.
